#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   Issue #350 is still open: on Windows, the code here causes it to link
   with PYTHON36.DLL (for example) instead of PYTHON3.DLL.  A fix was
   attempted in 164e526a5515 and 14ce6985e1c3, but reverted: virtualenv
   does not make PYTHON3.DLL available, and so the "correctly" compiled
   version would not run inside a virtualenv.  We will re-apply the fix
   after virtualenv has been fixed for some time.  For explanation, see
   issue #355.  For a workaround if you want PYTHON3.DLL and don't worry
   about virtualenv, see issue #350.  See also 'py_limited_api' in
   setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  include <pyconfig.h>
#  if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG)
#    define Py_LIMITED_API
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

#include <sdk/atomic.h>
#include <sdk/utils.h>

CCMRAM_VARIABLE static volatile uint32_t critical_cnt = 0;
CCMRAM_VARIABLE static volatile uint32_t critical_max = 0;

CCMRAM_FUCNTION void enter_critical(void) {
	//Mask priority, 4 is a ADC priority must be shifted by 4 x<<4
	//__set_BASEPRI(4<<4);

	__disable_irq();
	critical_cnt++;

	if (critical_cnt > critical_max) {
		critical_max = critical_cnt;
	}
}

CCMRAM_FUCNTION void exit_critical(void) {
	critical_cnt--;
	if (critical_cnt == 0) {
		__enable_irq();

		//Mask priority
		//__set_BASEPRI(0);
	}
}

uint32_t critical_get_max_queue_depth(void) {
	return critical_max;
}

void safe_increment(uint32_t *addr) {
	uint32_t new_value;
	do {
		new_value = __LDREXW(addr) + 1;
	} while (__STREXW(new_value, addr));
}

void safe_decrement(uint32_t *addr) {
	uint32_t new_value;
	do {
		new_value = __LDREXW(addr) - 1;
	} while (__STREXW(new_value, addr));
}


/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 30), // char const *()(void)
/*  1 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  2 */ _CFFI_OP(_CFFI_OP_FUNCTION, 3), // float()(float)
/*  3 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13), // float
/*  4 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  5 */ _CFFI_OP(_CFFI_OP_FUNCTION, 3), // float()(float, float)
/*  6 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13),
/*  7 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13),
/*  8 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  9 */ _CFFI_OP(_CFFI_OP_FUNCTION, 12), // int *()(void)
/* 10 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 11 */ _CFFI_OP(_CFFI_OP_FUNCTION, 15), // int()(int *)
/* 12 */ _CFFI_OP(_CFFI_OP_POINTER, 15), // int *
/* 13 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 14 */ _CFFI_OP(_CFFI_OP_FUNCTION, 15), // int()(int)
/* 15 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/* 16 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 17 */ _CFFI_OP(_CFFI_OP_FUNCTION, 49), // unsigned int()(void)
/* 18 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 19 */ _CFFI_OP(_CFFI_OP_FUNCTION, 51), // unsigned long long()(void)
/* 20 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 21 */ _CFFI_OP(_CFFI_OP_FUNCTION, 53), // unsigned long()(void)
/* 22 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 23 */ _CFFI_OP(_CFFI_OP_FUNCTION, 55), // void()(unsigned int *)
/* 24 */ _CFFI_OP(_CFFI_OP_POINTER, 49), // unsigned int *
/* 25 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 26 */ _CFFI_OP(_CFFI_OP_FUNCTION, 55), // void()(void)
/* 27 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 28 */ _CFFI_OP(_CFFI_OP_POINTER, 31), // char *
/* 29 */ _CFFI_OP(_CFFI_OP_POINTER, 0), // char const *(*)(void)
/* 30 */ _CFFI_OP(_CFFI_OP_POINTER, 31), // char const *
/* 31 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 32 */ _CFFI_OP(_CFFI_OP_POINTER, 2), // float(*)(float)
/* 33 */ _CFFI_OP(_CFFI_OP_POINTER, 5), // float(*)(float, float)
/* 34 */ _CFFI_OP(_CFFI_OP_POINTER, 9), // int *(*)(void)
/* 35 */ _CFFI_OP(_CFFI_OP_POINTER, 11), // int(*)(int *)
/* 36 */ _CFFI_OP(_CFFI_OP_POINTER, 14), // int(*)(int)
/* 37 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 15), // long double
/* 38 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 11), // long long
/* 39 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 9), // long
/* 40 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // max_align_t
/* 41 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 5), // short
/* 42 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 3), // signed char
/* 43 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // struct __lc_time_data
/* 44 */ _CFFI_OP(_CFFI_OP_POINTER, 45), // struct threadlocaleinfostruct *
/* 45 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 2), // struct threadlocaleinfostruct
/* 46 */ _CFFI_OP(_CFFI_OP_POINTER, 47), // struct threadmbcinfostruct *
/* 47 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 3), // struct threadmbcinfostruct
/* 48 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 4), // unsigned char
/* 49 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 8), // unsigned int
/* 50 */ _CFFI_OP(_CFFI_OP_POINTER, 19), // unsigned long long(*)(void)
/* 51 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 12), // unsigned long long
/* 52 */ _CFFI_OP(_CFFI_OP_POINTER, 21), // unsigned long(*)(void)
/* 53 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 10), // unsigned long
/* 54 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 6), // unsigned short
/* 55 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_max_align_t(max_align_t *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->__max_align_ll) | 0);  /* check that 'max_align_t.__max_align_ll' is an integer */
  { long double *tmp = &p->__max_align_ld; (void)tmp; }
}
struct _cffi_align_typedef_max_align_t { char x; max_align_t y; };

static struct _cffi_externpy_s _cffi_externpy____mingw_get_crt_info =
  { "atomic.__mingw_get_crt_info", (int)sizeof(char const *), 0, 0 };

char const * __mingw_get_crt_info(void)
{
  char a[8];
  char *p = a;
  _cffi_call_python(&_cffi_externpy____mingw_get_crt_info, p);
  return *(char const * *)p;
}

static struct _cffi_externpy_s _cffi_externpy____threadhandle =
  { "atomic.__threadhandle", (int)sizeof(unsigned long long), 0, 0 };

unsigned long long __threadhandle(void)
{
  char a[8];
  char *p = a;
  _cffi_call_python(&_cffi_externpy____threadhandle, p);
  return *(unsigned long long *)p;
}

static struct _cffi_externpy_s _cffi_externpy____threadid =
  { "atomic.__threadid", (int)sizeof(unsigned long), 0, 0 };

unsigned long __threadid(void)
{
  char a[8];
  char *p = a;
  _cffi_call_python(&_cffi_externpy____threadid, p);
  return *(unsigned long *)p;
}

static struct _cffi_externpy_s _cffi_externpy___errno =
  { "atomic._errno", (int)sizeof(int *), 0, 0 };

int * _errno(void)
{
  char a[8];
  char *p = a;
  _cffi_call_python(&_cffi_externpy___errno, p);
  return *(int * *)p;
}

static struct _cffi_externpy_s _cffi_externpy___get_errno =
  { "atomic._get_errno", (int)sizeof(int), 0, 0 };

int _get_errno(int * a0)
{
  char a[8];
  char *p = a;
  *(int * *)(p + 0) = a0;
  _cffi_call_python(&_cffi_externpy___get_errno, p);
  return *(int *)p;
}

static struct _cffi_externpy_s _cffi_externpy___set_errno =
  { "atomic._set_errno", (int)sizeof(int), 0, 0 };

int _set_errno(int a0)
{
  char a[8];
  char *p = a;
  *(int *)(p + 0) = a0;
  _cffi_call_python(&_cffi_externpy___set_errno, p);
  return *(int *)p;
}

static struct _cffi_externpy_s _cffi_externpy__fast_atan2f =
  { "atomic.fast_atan2f", (int)sizeof(float), 0, 0 };

float fast_atan2f(float a0, float a1)
{
  char a[16];
  char *p = a;
  *(float *)(p + 0) = a0;
  *(float *)(p + 8) = a1;
  _cffi_call_python(&_cffi_externpy__fast_atan2f, p);
  return *(float *)p;
}

static struct _cffi_externpy_s _cffi_externpy__fast_atan2f_sec =
  { "atomic.fast_atan2f_sec", (int)sizeof(float), 0, 0 };

float fast_atan2f_sec(float a0, float a1)
{
  char a[16];
  char *p = a;
  *(float *)(p + 0) = a0;
  *(float *)(p + 8) = a1;
  _cffi_call_python(&_cffi_externpy__fast_atan2f_sec, p);
  return *(float *)p;
}

static struct _cffi_externpy_s _cffi_externpy__fast_inv_sqrtf =
  { "atomic.fast_inv_sqrtf", (int)sizeof(float), 0, 0 };

float fast_inv_sqrtf(float a0)
{
  char a[8];
  char *p = a;
  *(float *)(p + 0) = a0;
  _cffi_call_python(&_cffi_externpy__fast_inv_sqrtf, p);
  return *(float *)p;
}

static struct _cffi_externpy_s _cffi_externpy__fast_log =
  { "atomic.fast_log", (int)sizeof(float), 0, 0 };

float fast_log(float a0)
{
  char a[8];
  char *p = a;
  *(float *)(p + 0) = a0;
  _cffi_call_python(&_cffi_externpy__fast_log, p);
  return *(float *)p;
}

static struct _cffi_externpy_s _cffi_externpy__fast_norm_angle_deg =
  { "atomic.fast_norm_angle_deg", (int)sizeof(float), 0, 0 };

float fast_norm_angle_deg(float a0)
{
  char a[8];
  char *p = a;
  *(float *)(p + 0) = a0;
  _cffi_call_python(&_cffi_externpy__fast_norm_angle_deg, p);
  return *(float *)p;
}

static struct _cffi_externpy_s _cffi_externpy__fast_norm_angle_rad =
  { "atomic.fast_norm_angle_rad", (int)sizeof(float), 0, 0 };

float fast_norm_angle_rad(float a0)
{
  char a[8];
  char *p = a;
  *(float *)(p + 0) = a0;
  _cffi_call_python(&_cffi_externpy__fast_norm_angle_rad, p);
  return *(float *)p;
}

static void _cffi_d___debugbreak(void)
{
  __debugbreak();
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f___debugbreak(PyObject *self, PyObject *noarg)
{

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { __debugbreak(); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  (void)noarg; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f___debugbreak _cffi_d___debugbreak
#endif

static unsigned int _cffi_d_critical_get_max_queue_depth(void)
{
  return critical_get_max_queue_depth();
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_critical_get_max_queue_depth(PyObject *self, PyObject *noarg)
{
  unsigned int result;
  PyObject *pyresult;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = critical_get_max_queue_depth(); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  (void)noarg; /* unused */
  pyresult = _cffi_from_c_int(result, unsigned int);
  return pyresult;
}
#else
#  define _cffi_f_critical_get_max_queue_depth _cffi_d_critical_get_max_queue_depth
#endif

static void _cffi_d_enter_critical(void)
{
  enter_critical();
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_enter_critical(PyObject *self, PyObject *noarg)
{

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { enter_critical(); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  (void)noarg; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_enter_critical _cffi_d_enter_critical
#endif

static void _cffi_d_exit_critical(void)
{
  exit_critical();
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_exit_critical(PyObject *self, PyObject *noarg)
{

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { exit_critical(); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  (void)noarg; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_exit_critical _cffi_d_exit_critical
#endif

static void _cffi_d_safe_decrement(unsigned int * x0)
{
  safe_decrement(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_safe_decrement(PyObject *self, PyObject *arg0)
{
  unsigned int * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(24), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (unsigned int *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(24), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { safe_decrement(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_safe_decrement _cffi_d_safe_decrement
#endif

static void _cffi_d_safe_increment(unsigned int * x0)
{
  safe_increment(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_safe_increment(PyObject *self, PyObject *arg0)
{
  unsigned int * x0;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(24), arg0, (char **)&x0);
  if (datasize != 0) {
    x0 = ((size_t)datasize) <= 640 ? (unsigned int *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(24), arg0, (char **)&x0,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { safe_increment(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_safe_increment _cffi_d_safe_increment
#endif

static const struct _cffi_global_s _cffi_globals[] = {
  { "__debugbreak", (void *)_cffi_f___debugbreak, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_N, 26), (void *)_cffi_d___debugbreak },
  { "__mingw_get_crt_info", (void *)&_cffi_externpy____mingw_get_crt_info, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 29), (void *)__mingw_get_crt_info },
  { "__threadhandle", (void *)&_cffi_externpy____threadhandle, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 50), (void *)__threadhandle },
  { "__threadid", (void *)&_cffi_externpy____threadid, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 52), (void *)__threadid },
  { "_errno", (void *)&_cffi_externpy___errno, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 34), (void *)_errno },
  { "_get_errno", (void *)&_cffi_externpy___get_errno, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 35), (void *)_get_errno },
  { "_set_errno", (void *)&_cffi_externpy___set_errno, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 36), (void *)_set_errno },
  { "critical_get_max_queue_depth", (void *)_cffi_f_critical_get_max_queue_depth, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_N, 17), (void *)_cffi_d_critical_get_max_queue_depth },
  { "enter_critical", (void *)_cffi_f_enter_critical, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_N, 26), (void *)_cffi_d_enter_critical },
  { "exit_critical", (void *)_cffi_f_exit_critical, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_N, 26), (void *)_cffi_d_exit_critical },
  { "fast_atan2f", (void *)&_cffi_externpy__fast_atan2f, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 33), (void *)fast_atan2f },
  { "fast_atan2f_sec", (void *)&_cffi_externpy__fast_atan2f_sec, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 33), (void *)fast_atan2f_sec },
  { "fast_inv_sqrtf", (void *)&_cffi_externpy__fast_inv_sqrtf, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 32), (void *)fast_inv_sqrtf },
  { "fast_log", (void *)&_cffi_externpy__fast_log, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 32), (void *)fast_log },
  { "fast_norm_angle_deg", (void *)&_cffi_externpy__fast_norm_angle_deg, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 32), (void *)fast_norm_angle_deg },
  { "fast_norm_angle_rad", (void *)&_cffi_externpy__fast_norm_angle_rad, _CFFI_OP(_CFFI_OP_EXTERN_PYTHON, 32), (void *)fast_norm_angle_rad },
  { "safe_decrement", (void *)_cffi_f_safe_decrement, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 23), (void *)_cffi_d_safe_decrement },
  { "safe_increment", (void *)_cffi_f_safe_increment, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 23), (void *)_cffi_d_safe_increment },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "__max_align_ll", offsetof(max_align_t, __max_align_ll),
                      sizeof(((max_align_t *)0)->__max_align_ll),
                      _CFFI_OP(_CFFI_OP_NOOP, 38) },
  { "__max_align_ld", offsetof(max_align_t, __max_align_ld),
                      sizeof(((max_align_t *)0)->__max_align_ld),
                      _CFFI_OP(_CFFI_OP_NOOP, 37) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "$max_align_t", 40, _CFFI_F_CHECK_FIELDS,
    sizeof(max_align_t), offsetof(struct _cffi_align_typedef_max_align_t, y), 0, 2 },
  { "__lc_time_data", 43, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "threadlocaleinfostruct", 45, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "threadmbcinfostruct", 47, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "__gnuc_va_list", 28 },
  { "__time32_t", 39 },
  { "__time64_t", 38 },
  { "errno_t", 15 },
  { "int16_t", 41 },
  { "int32_t", 15 },
  { "int64_t", 38 },
  { "int8_t", 42 },
  { "int_fast16_t", 41 },
  { "int_fast32_t", 15 },
  { "int_fast64_t", 38 },
  { "int_fast8_t", 42 },
  { "int_least16_t", 41 },
  { "int_least32_t", 15 },
  { "int_least64_t", 38 },
  { "int_least8_t", 42 },
  { "intmax_t", 38 },
  { "intptr_t", 38 },
  { "max_align_t", 40 },
  { "pthreadlocinfo", 44 },
  { "pthreadmbcinfo", 46 },
  { "ptrdiff_t", 38 },
  { "rsize_t", 51 },
  { "size_t", 51 },
  { "ssize_t", 38 },
  { "time_t", 38 },
  { "uint16_t", 54 },
  { "uint32_t", 49 },
  { "uint64_t", 51 },
  { "uint8_t", 48 },
  { "uint_fast16_t", 54 },
  { "uint_fast32_t", 49 },
  { "uint_fast64_t", 51 },
  { "uint_fast8_t", 48 },
  { "uint_least16_t", 54 },
  { "uint_least32_t", 49 },
  { "uint_least64_t", 51 },
  { "uint_least8_t", 48 },
  { "uintmax_t", 51 },
  { "uintptr_t", 51 },
  { "va_list", 28 },
  { "wchar_t", 54 },
  { "wctype_t", 54 },
  { "wint_t", 54 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  NULL,  /* no enums */
  _cffi_typenames,
  18,  /* num_globals */
  4,  /* num_struct_unions */
  0,  /* num_enums */
  44,  /* num_typenames */
  NULL,  /* no includes */
  56,  /* num_types */
  1,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_atomic(const void *p[])
{
    if (((intptr_t)p[0]) >= 0x0A03) {
        _cffi_call_python_org = (void(*)(struct _cffi_externpy_s *, char *))p[1];
    }
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_atomic(void) { return NULL; }
#  else
     initatomic(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_atomic(void)
{
  return _cffi_init("atomic", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initatomic(void)
{
  _cffi_init("atomic", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
