#ifndef DEBUG_APP_H_
#define DEBUG_APP_H_

#define DEBUG_TEST_ENABLE	0

//Critical error definition
#define DEBUG_CRITICAL_ERROR_LIST(NAME)						\
		NAME(CLOCK_SPEED_ERROR)								\
		NAME(CLOCK_SOURCE_ERROR)							\
		NAME(NMI_ERROR)										\
		NAME(HARDFAULT_ERROR)								\
		NAME(MEMMANAGE_ERROR)								\
		NAME(BUSFAULT_ERROR)								\
		NAME(USAGEFAULT_HANDLER)							\
		NAME(SVC_ERROR)										\
		NAME(DEBUGMON_ERROR)								\
		NAME(PENDSV_ERROR)									\
		NAME(DRV8301_SPI_READ_ERROR)						\
		NAME(DMA_TX_OVERRUN_ERROR)							\
		NAME(ROTOR_INJECTED_PHASE_ERROR)					\
		NAME(BUZZER_SOUND_NOT_RECOGNISED)					\
		NAME(SLAVE_SELECTED_NOT_SUPPORTED)					\
		NAME(SPI_TRANSACTION_BUFFER_OVERFLOW)				\
		NAME(PRESSURE_SENOR_NOT_DETECTED)					\
		NAME(SERVO_POSITION_NOT_DEFINED)					\
		NAME(SERVO_ANGLE_OUT_OF_RANGE)						\
		NAME(IMU_SENOR_NOT_DETECTED)						\
		NAME(DEBUG_RYBOS_TASK_LIST_LENGTH_ERROR)			\
		NAME(RYBOS_TASK_MARKER_STACK_OVERLOW)				\
		NAME(RYBOS_TASK_MARKER_ERROR)						\
		NAME(DRV8301_READ_FRAME_FAULT)						\
		NAME(ADC234_OVERRUN_ERROR)							\
		NAME(ADC1_OVERRUN_ERROR)							\
		NAME(BLDC_STATE_ERROR)								\
		NAME(BLDC_PHASE_CNT_ERROR)							\
		NAME(SI4468_CMD_ERROR_RESP)							\
		NAME(RADIO_SM_RX_CMD_NOT_SUPPORTED)					\
		NAME(RADIO_SM_TX_CMD_NOT_SUPPORTED)					\
		NAME(UART_FRAME_MESSAGE_OVERLENGTH)					\
		NAME(SI4468_COMMAND_LENGTH_ERROR)					\
		NAME(RADIO_CYCLIC_BUFFER_OVERFLOW)					\
		NAME(RADIO_TX_SM_STATE_NOT_SUPPORTED)				\
		NAME(RADIO_RX_SM_STATE_NOT_SUPPORTED)				\
		NAME(ADC_TIMEOUT_ERROR)								\
		NAME(SI4468_CMD_ERROR_IRQ_INIT)						\
		NAME(RADIO_SM_ERROR_CMD_NOT_SUPPORTED)				\
		NAME(RC_CONTROL_CRC_ERROR)							\
		NAME(CYCLIC_BUFFER_OVERFLOW_CRITICAL)				\
		NAME(VIBRATOR_SOUND_NOT_RECOGNISED)					\
		NAME(CYCLIC_PTR_OVERFLOW_CRITICAL)					\
		NAME(CYCLIC_BYTE_OVERFLOW_CRITICAL)					\
		NAME(ADC_OFFSET_NOT_DEFINE_FOR_THIS_DEVICE)			\
		NAME(DISPLAY_TYPE_NOT_SUPORTTED)					\
		NAME(PID_TYPE_FRAME_NOT_SUPPORTED)					\
		NAME(FRAME_DECODING_STATE_MASHINE_NO_STATE)			\
		NAME(DEBUG_ERROR_NOT_HANDLE)						\
		NAME(FRAME_SCOPE_LOST)								\
		NAME(BLDC_SECTOR_NOT_SUPPORTED)

//Non critical error definition
#define DEBUG_MESSAGE_ERROR_LIST(NAME)						\
		NAME(SI4468_CMD_ERROR_IRQ)							\
		NAME(SI4468_PACKET_LOST_ERROR)						\
		NAME(FRAME_MESSAGE_OVERLENGTH)						\
		NAME(FRAME_TYPE_NOT_SUPPORTED)						\
		NAME(FRAME_BUFFER_OVERFLOW)							\
		NAME(FRAME_CRC_ERROR)								\
		NAME(SI4468_RETRANSMITTION)							\
		NAME(SI4468_RETRANSMITTION_LIMIT_REACHED)			\
		NAME(RADIO_TX_SM_RETRANSMITTION_LIMIT_REACHED)		\
		NAME(RADIO_RX_SM_RETRANSMITTION_LIMIT_REACHED)		\
		NAME(RADIO_RX_FRAME_SIZE_OUT_OF_RANGE)				\
		NAME(SI4468_PACKET_CRC_ERROR_IRQ)					\
		NAME(CYCLIC_BUFFER_OVERFLOW_NO_CRITICAL)			\
		NAME(CYCLIC_PTR_OVERFLOW_NO_CRITICAL)				\
		NAME(CYCLIC_BYTE_OVERFLOW_NO_CRITICAL)

#endif
