#ifndef TTINGS_DEBUG_ERROR_LIST_H_
#define DEBUG_ERROR_LIST_H_

//Critical error definition
#define DEBUG_CRITICAL_ERROR_LIST(name)						\
		name(NO_ERROR)										\
		name(CLOCK_SPEED_ERROR)								\
		name(CLOCK_SOURCE_ERROR)							\
		name(NMI_ERROR)										\
		name(HARDFAULT_ERROR)								\
		name(MEMMANAGE_ERROR)								\
		name(BUSFAULT_ERROR)								\
		name(USAGEFAULT_HANDLER)							\
		name(SVC_ERROR)										\
		name(DEBUGMON_ERROR)								\
		name(PENDSV_ERROR)									\
		name(DRV8301_SPI_READ_ERROR)						\
		name(DMA_TX_OVERRUN_ERROR)							\
		name(ROTOR_INJECTED_PHASE_ERROR)					\
		name(BUZZER_SOUND_NOT_RECOGNISED)					\
		name(SLAVE_SELECTED_NOT_SUPPORTED)					\
		name(SPI_TRANSACTION_BUFFER_OVERFLOW)				\
		name(PRESSURE_SENOR_NOT_DETECTED)					\
		name(SERVO_POSITION_NOT_DEFINED)					\
		name(IMU_SENOR_NOT_DETECTED)						\
		name(RYBOS_TASK_LIST_OUT_OF_RANGE)					\
		name(RYBOS_TASK_MARKER_STACK_OVERLOW)				\
		name(RYBOS_TASK_MARKER_ERROR)						\
		name(DRV8301_READ_FRAME_FAULT)						\
		name(ADC234_OVERRUN_ERROR)							\
		name(ADC1_OVERRUN_ERROR)							\
		name(BLDC_STATE_ERROR)								\
		name(BLDC_PHASE_CNT_ERROR)							\
		name(SI4468_CMD_ERROR_RESP)							\
		name(RADIO_SM_RX_CMD_NOT_SUPPORTED)					\
		name(RADIO_SM_TX_CMD_NOT_SUPPORTED)					\
		name(SI4468_COMMAND_LENGTH_ERROR)					\
		name(RADIO_CYCLIC_BUFFER_OVERFLOW)					\
		name(RADIO_TX_SM_STATE_NOT_SUPPORTED)				\
		name(RADIO_RX_SM_STATE_NOT_SUPPORTED)				\
		name(ADC_TIMEOUT_ERROR)								\
		name(SI4468_CMD_ERROR_IRQ_INIT)						\
		name(RADIO_SM_ERROR_CMD_NOT_SUPPORTED)				\
		name(RC_CONTROL_CRC_ERROR)							\
		name(CYCLIC_BUFFER_OVERFLOW_CRITICAL)				\
		name(VIBRATOR_SOUND_NOT_RECOGNISED)					\
		name(CYCLIC_PTR_OVERFLOW_CRITICAL)					\
		name(CYCLIC_BYTE_OVERFLOW_CRITICAL)					\
		name(ADC_OFFSET_NOT_DEFINE_FOR_THIS_DEVICE)			\
		name(DISPLAY_TYPE_NOT_SUPORTTED)					\
		name(PID_TYPE_FRAME_NOT_SUPPORTED)					\
		name(FRAME_DECODING_STATE_MASHINE_NO_STATE)			\
		name(FRAME_SCOPE_LOST)								\
		name(BLDC_SECTOR_NOT_SUPPORTED)						\
		name(PID_TYPE_NOT_SUPPORTED)						\
		name(SCOPE_MORE_THAN_ONE_MODE_USED)					\
		name(SCOPE_SM_STATE_NOT_SUPPORTED)					\
		name(SCOPE_BUFFER_OVERFLOW)							\
		name(SI4468_NIRQ_NOT_IMPLEMENTED)					\
		name(SI4468_CTS_NOT_IMPLEMENTED)

//Non critical error definition
#define DEBUG_MESSAGE_ERROR_LIST(name)						\
		name(SI4468_CMD_ERROR_IRQ)							\
		name(SI4468_PACKET_LOST_ERROR)						\
		name(FRAME_MESSAGE_OVERLENGTH)						\
		name(FRAME_TYPE_NOT_SUPPORTED)						\
		name(FRAME_BUFFER_OVERFLOW)							\
		name(FRAME_CRC_ERROR)								\
		name(SI4468_RETRANSMITTION)							\
		name(SI4468_RETRANSMITTION_LIMIT_REACHED)			\
		name(RADIO_TX_SM_RETRANSMITTION_LIMIT_REACHED)		\
		name(RADIO_RX_SM_RETRANSMITTION_LIMIT_REACHED)		\
		name(RADIO_RX_FRAME_SIZE_OUT_OF_RANGE)				\
		name(SI4468_PACKET_CRC_ERROR_IRQ)					\
		name(CYCLIC_BUFFER_OVERFLOW_NO_CRITICAL)			\
		name(CYCLIC_PTR_OVERFLOW_NO_CRITICAL)				\
		name(CYCLIC_BYTE_OVERFLOW_NO_CRITICAL)				\
		name(FRAME_TX_BUFFER_OVERFLOW)						\
		name(UART_FRAME_MESSAGE_OVERLENGTH)

#endif
